name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Eslint
        run: |
          yarn
          yarn lint

      - name: Testing
        run: |
          yarn test
